routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('weather-forecast');
});


Route::resource('weather-forecast','WeatherForecastController');

app/ApiSource.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ApiSource extends Model
{
    protected $table = 'api_sources';
    
    protected $fillable = ['result_id','source_id','weather_description','temperature','pressure','humidity'];
    
}

app/Result.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Result extends Model
{
    protected $fillable = ['city','country','avg_temp'];

    public function getSources()
    {
        return $this->hasMany('App\ApiSource','result_id','id');
    }
    
}

app/Source.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Source extends Model
{
    protected $fillable = ['api_name'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/WeatherForecastController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use App\Traits\ApiTrait;
use App\Result;

class WeatherForecastController extends Controller
{

    use ApiTrait; 
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    private $api1_key, $api2_key;  

    public function __construct(){

        $this->api1_key = '439d4b804bc8187953eb36d2a8c26a02';
        //$api1_key - this api key is from OPEN WEATHER MAP API
        $this->api2_key = '0e79f2ef04eb0a7e1dc159eb8c71bda9';
        //$api2_key - this api key is from WEATHER STACK API

        $this->results = Result::orderBy('created_at','desc')->get();      
        
    }
    
    public function index()
    {
       // $data =  Http::get('openweathermap.org/data/2.5/weather?q='.$city.','.$country.'&appid=439d4b804bc8187953eb36d2a8c26a02')->json();
     
       return view('modules.weather-forecast.index',['results' => $this->results]);

       
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $city = $request->city;
        $country = $request->country;
       
        $api1 =  $this->getApiData($city,$country,$this->api1_key,1);

        
        $api2 =  $this->getApiData($city,$country,$this->api2_key,2);
        
        if($api1['cod'] == 200 )
        {
            $temp_avg = $this->getAvgTemp($api1['main']['temp'],$api2['current']['temperature']);

            $this->storeData($city, $country, $temp_avg, $api1, $api2);
            
        }       

        return view('modules.weather-forecast.results',['api1' => $api1 ,'api2' => $api2,'city' => $city,'country' =>$country, 'temp_avg' => $temp_avg]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/includes/footer.blade.php
   <!-- Mainly scripts -->
   
   <script src="http://code.jquery.com/jquery-latest.js"></script>
   <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script> -->
   <script src="http://malsup.github.com/jquery.form.js"></script>
    <!--Datatables -->
    <script src="{{ asset('inspinia_admin/js/plugins/dataTables/datatables.min.js') }}"></script>
    
    
     <!-- Tinycon -->
     <script src="{{ asset('inspinia_admin/js/plugins/tinycon/tinycon.min.js') }}"></script>

      <!-- Sweet alert -->
    <script src="{{ asset('inspinia_admin/js/plugins/sweetalert/sweetalert.min.js') }}"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>   

    

    
  
   
   

resources/views/includes/header.blade.php
<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>Ricky Api Test - Weather Forecast</title>

    <link href="{{ asset('inspinia_admin/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('inspinia_admin/font-awesome/css/font-awesome.css') }}" rel="stylesheet">
    <link href="{{ asset('inspinia_admin/css/plugins/dataTables/datatables.min.css') }}" rel="stylesheet">
    
    <!-- Ladda style -->
    <link href="{{ asset('inspinia_admin/css/plugins/ladda/ladda-themeless.min.css') }}" rel="stylesheet">

    <!-- Toastr style -->
    <link href="{{ asset('inspinia_admin/css/plugins/toastr/toastr.min.css') }}" rel="stylesheet"> 
    <!-- iCheck style -->
    
    <link href="{{ asset('inspinia_admin/css/style.css') }}" rel="stylesheet">



    <!-- Sweet Alert -->
    <link href="{{ asset('inspinia_admin/css/plugins/sweetalert/sweetalert.css') }}" rel="stylesheet">

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css">   

</head>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html>

@include("includes.header")

<body class="top-navigation">

    <div id="wrapper">
        <div id="page-wrapper" class="gray-bg">
            <div class="row border-bottom white-bg">
            <nav class="navbar navbar-static-top" role="navigation">
                <div class="navbar-header">
                    <div class="row">
                        <div class="col-lg-12">
                        <div class="navbar-brand">Weather Forecast By Ricky Millang </div> 
                        </div>
                    </div>
                </div>
                
            </nav>
            </div>
          @yield("content")

        </div>
    </div>
    
   @include("includes.footer") 
    
   @yield("custom_js")
</body>

</html>

resources/views/modules/weather-forecast/index.blade.php
@extends('layouts.master')

@section('content')
<div class="wrapper wrapper-content">
     <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Search Weather Forecast</h5>
                        <div class="ibox-tools">                              
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <form id="search" role="form" action="{{ route('weather-forecast.store') }}" method="POST" class="form-horizontal">
                               @csrf
                                <div class="col-md-5"> 
                                    <div class="form-group">
                                    
                                        <input type="text" placeholder="Enter city" id="city" name ="city"
                                            class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-5">    
                                    <div class="form-group">
                                        <label for="country" class="sr-only">Country</label>
                                        <input type="text" placeholder="Enter country" id="country" name="country"
                                            class="form-control ">
                                    </div>
                                </div>   
                                <div class="col-md-2">   
                                    <div class="form-group">
                                    <button class="btn btn-primary btn-block">Search</button>
                                    </div>
                                </div>   
                            </form>
                        </div>
                        <div class="loader" >
                            <div class="sk-spinner sk-spinner-rotating-plane loader" ></div>
                        </div>
                        <div class="row" id="targetlayer">
                            
                        </div>

                    </div>
                </div>
            </div>          
        </div>

        <div class="row">

            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Previous Weather Forecast Results </h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        
                        </div>
                    </div>
                    <div class="ibox-content">
                        
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                <tr>                                    
                                    <th>City </th>
                                    <th>Country </th>
                                    <th>Source Api1 Temp </th>
                                    <th>Source Api2 Temp </th>
                                    <th>Average Temp</th>
                                    <th>Date Search</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($results as $r) 
                                <tr>
                                    <td>{{ $r->city }}</td>
                                    <td>{{ $r->country }}</td>
                                    <td style="text-align:center">{{ ($r->getSources->where('source_id',1)->first())->temperature }}</td>
                                    <td style="text-align:center">{{ ($r->getSources->where('source_id',2)->first())->temperature}}</td>
                                    <td style="text-align:center">{{ $r->avg_temp}}</td>

                                    <td>{{ date('M d,Y h:i a',strtotime($r->created_at)) }}</td>                                  
                                </tr>
                                @endforeach
                                
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>

        </div>

    </div>

</div>
<div class="footer">
    <div class="pull-right">
        Ricky Millang - Php Developer
    </div>
    <div>
        <strong>Api Exam</strong> Link365 &copy; 2020
    </div>
</div>
@endsection

@section('custom_js')
<script>
         $(document).ready(function() { 

            toastr.options = {
                              "closeButton": true,
                              "debug": false,
                              "newestOnTop": false,
                              "progressBar": false,
                              "positionClass": "toast-top-right",
                              "preventDuplicates": false,
                              "onclick": null,
                              "showDuration": "300",
                              "hideDuration": "1000",
                              "timeOut": "15000",
                              "extendedTimeOut": "1000",
                              "showEasing": "swing",
                              "hideEasing": "linear",
                              "showMethod": "fadeIn",
                              "hideMethod": "fadeOut"
                              };   

            $('.loader').hide();

         
            $('#search').submit(function(e) {	
                 var city = $("#city").val();
                 var country = $("#country").val();

                $('#targetlayer').html(""); 
                    
                    e.preventDefault();
                   
                    $(this).ajaxSubmit({ 
                        target:   '#targetLayer', 
                        dataType: 'text',
                        beforeSubmit: function() {
                            $('.loader').show();
                        },
                        uploadProgress: function (event, position, total, percentComplete){	
                           
                           $('.loader').show();
                        },
                        success:function (result){
                            toastr["success"]("Weather forecast result automatically save and listed in the previous forecast results table below. You can see the newly saved data if you refresh the page!");
                            $('.loader').hide();
                            $('#targetlayer').html(result);
                           
                        },
                        error:function(error){
                            toastr["error"](city+" city does not belong to "+country+" country!");
                            $('.loader').hide();
                            console.log(error);
                           
                        },
                        resetForm: true 
                    }); 
                    return false; 
                
            });
        });
   </script>
@endsection

resources/views/modules/weather-forecast/results.blade.php
<div class="col-md-6">
    <h2>Source Api1</h2>
    <small><strong> Open Weather Map Api </strong></small>
    <ul class="list-group clear-list m-t">
        <li class="list-group-item fist-item">
            <span class="pull-right">
                {{ ucfirst($city) }}
            </span>
            <span class="label label-success "><i class="fa fa-map-marker"></i></span> City
        </li>
        <li class="list-group-item">
            <span class="pull-right">
                {{ ucfirst($country) }}
            </span>
            <span class="label label-info"><i class="fa fa-flag"></i></span> Country
        </li>
        <li class="list-group-item">
            <span class="pull-right">
                {{ ucfirst($api1['weather'][0]['description']) }}
            </span>
            <span class="label label-primary"><i class="fa fa-cloud"></i></span> Weather Description
        </li>
        <li class="list-group-item">
            <span class="pull-right">
                {{ $api1['main']['temp'] }}
            </span>
            <span class="label label-danger"><i class="fa fa-sun-o"></i></span> Temperature
        </li>        
        <li class="list-group-item">
            <span class="pull-right">
                {{ $api1['main']['pressure'] }}
            </span>
            <span class="label label-success"><i class="fa fa-dashboard"></i></span> Pressure
        </li>
        <li class="list-group-item">
            <span class="pull-right">
                {{ $api1['main']['humidity'] }}
            </span>
            <span class="label label-danger"><i class="fa fa-tint"></i></span> Humidity
        </li>
    </ul>
</div>
<div class="col-md-6">
    <h2>Source Api2</h2>
    <small><strong> Weather Stack Api </strong></small>
    <ul class="list-group clear-list m-t">
    <li class="list-group-item fist-item">
            <span class="pull-right">
                {{ ucfirst($city) }}
            </span>
            <span class="label label-success "><i class="fa fa-map-marker"></i></span> City
        </li>
        <li class="list-group-item">
            <span class="pull-right">
                {{ ucfirst($country) }}
            </span>
            <span class="label label-info"><i class="fa fa-flag"></i></span> Country
        </li>
        <li class="list-group-item">
            <span class="pull-right">
                {{ ucfirst($api2['current']['weather_descriptions'][0]) }}
            </span>
            <span class="label label-primary"><i class="fa fa-cloud"></i></span> Weather Description
        </li>
        <li class="list-group-item">
            <span class="pull-right">
                {{ $api2['current']['temperature'] }}
            </span>
            <span class="label label-danger"><i class="fa fa-sun-o"></i></span> Temperature
        </li>

        <li class="list-group-item">
            <span class="pull-right">
                {{ $api2['current']['pressure'] }}
            </span>
            <span class="label label-success"><i class="fa fa-dashboard"></i></span> Pressure
        </li>
        <li class="list-group-item">
            <span class="pull-right">
                {{ $api2['current']['humidity'] }}
            </span>
            <span class="label label-danger"><i class="fa fa-tint"></i></span> Humidity
        </li>
    </ul>
    
</div>
<button class="btn btn-primary btn-block">Average Temperature : <b>{{ $temp_avg }}</b></button>